ASPracticeCore/Areas/Accounts/Controllers/AccessController.cs
using ASPracticeCore.Areas.Accounts.Models;
using ASPracticeCore.DAL;
using ASPracticeCore.Models;
using ASPracticeCore.Repositories;
using ASPracticeCore.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;


namespace ASPracticeCore.Areas.Accounts.Controllers
{

    [AllowAnonymous]
    [Area("Accounts")]
    public class AccessController : Controller
    {
        readonly ApplicationContext _context;

        public AccessController(ApplicationContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("Accounts/Access/Login")]
        public IActionResult Login(string statusMessage)
        {

            ViewData["isError"] = false;
            if (statusMessage != null)
            {

                string classifier = statusMessage.Split('_')[0];
                if (classifier.Equals(Constants.FAILED))
                {
                    ViewData["isError"] = true;
                }
                ViewBag.statusMessage = statusMessage.Split('_')[1];

            }

            return View();
        }

        [HttpPost]
        [Route("Accounts/Access/Login")]
        public async Task<IActionResult> Login(string email, string password)
        {

            AccountRepository repo = new AccountRepository();
            //check its existence in the database
            UserAccount account = repo.Authenticate(email, password);

            if (account == null)
            {
                //no match, return to login with message
                string failMessage = Constants.FAILED + "_Incorrect username or password.";
                return RedirectToAction("Login", new { statusMessage = failMessage });
            }

            //Match - create auth cookie with unique key in it, save unique key along with user id to the database
            await Util.ControllerUtil.SignInAsync(account.Id, account.Name);
            return RedirectToAction("Index", "Home", new {personName = account.Name});
        }

        [Route("Accounts/Access/Register")]
        public IActionResult Register(UserAccount account)
        {

            Util.DisplayObjectProperties(account);

            RepositoryReflection repo = new RepositoryReflection();
            string addStatus = repo.Add(account);

            if (addStatus != Constants.SUCCESS)
            {
                return RedirectToAction("Error", "Home");
            }

            string statusMessage = Constants.SUCCESS + "_" + account.Email + " added successfully!";
            return RedirectToAction("Login", new { statusMessage });
        }


        
        [Authorize]
        [Route("Accounts/Access/Logout")]
        public async Task<IActionResult> LogoutAsync()
        {
            //clear the session data 
            //await HttpContext.Session.LoadAsync();
            //HttpContext.Session.Remove(Constants.KEY_USERID);
            //HttpContext.Session.Remove(Constants.KEY_USER_NAME);
            //HttpContext.Session.Clear();

            ////remove the session cookie in the response:
            //Response.Cookies.Delete(Constants.COOKIE_NAME_SESSION);

            //remove the auth cookie
            
            await Util.ControllerUtil.SignOutAsync(); //to delete the auth cookie
            

            return RedirectToAction("Login");
        }



    }
}

ASPracticeCore/Controllers/ShareableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPracticeCore.ViewModels;
using ASPracticeCore.Repositories;
using ASPracticeCore.Models;
using ASPracticeCore.Utils;
using Microsoft.AspNetCore.Mvc;
using ASPracticeCore.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;

namespace ASPracticeCore.Controllers
{

    public class ShareableController : Controller
    {

        readonly ApplicationContext _context;
        readonly IWebHostEnvironment _env;
        readonly IConfiguration _config;
        readonly IDataProtectionProvider _provider;
        public ShareableController(ApplicationContext context, IConfiguration config, IWebHostEnvironment env, IDataProtectionProvider provider)
        {
            //All supplied through DI
            _env = env;
            _config = config;
            _provider = provider;
            //controller does the disposing of the context
            _context = context;
        }

        public IActionResult UserShareables()
        {
            return View("Views/Shareable/UserShareables.cshtml");
        }
        public IActionResult ManageShareable()
        {
            return UserShareables();
        }
        [HttpGet]
        public IActionResult CreateShareable()
        {
            return UserShareables();
        }
        [HttpPost]
        public async Task<IActionResult> CreateShareable(AddShareableViewModel shareableVM)
        {
            //Save selected images to filesystem
            string savePath = _config.GetValue<string>("ImageSavePath");
            List<FilePath> files = await Util.ControllerUtil.SaveFilesToDisk(Request.Form.Files, savePath);

            int activeUserId = Convert.ToInt32(HttpContext.User.Identity.Name);
            Shareable shareable = new Shareable
            {
                Title = shareableVM.Title,
                Introduction = shareableVM.Introduction,
                DateTimeStamp = DateTime.Now,
                UserAccountId = activeUserId,
                Paragraphs = shareableVM.Paragraphs,
                FilePaths = files
            };

            //save entity to DB with EF repo (there are multiple repo types)
            var repo = new RepositoryEF(_context);
            string status = repo.Create(shareable);

            if (status == Constants.SUCCESS)
            {
                status += "_" + shareable.Title + " added successfully!";
            }

            return Json(status);

        }

        public async Task<IActionResult> UpdateShareable(Shareable update)
        {

                int activeUserId = Convert.ToInt32(HttpContext.User.Identity.Name);
                update.UserAccountId = activeUserId;
                update.DateTimeStamp = DateTime.Now;

                var repo = new RepositoryShareable();
                string status = await repo.UpdateExcludeImages(_context, update);


            return Json(status);

        }

        public async Task<IActionResult> DeleteShareable([FromBody] Shareable shareable)
        {

            var repo = new RepositoryEF(_context);
            string status = await repo.Delete<Shareable>(shareable.Id);

            if (status == Constants.SUCCESS)
            {
                //Since Delete() is generic, it doesn't have access to specific props like Title, we form the status message here
                status = StatusGenerator.getSuccessMessage($"{shareable.Title} was removed from your posts");
            }
            return Json(status);
        }

        public async Task<IActionResult> GetUserShareables()
        {
            int userId = Convert.ToInt32(HttpContext.User.Identity.Name);
            RepositoryReflection repo = new RepositoryReflection();
            var shareables = await repo.GetItemsOfOwnerAsync<Shareable>("useraccount", "shareable", userId);

            //get child properties:
            foreach (var shareable in shareables)
            {
                shareable.Paragraphs = await repo.GetItemsOfOwnerAsync<Paragraph>("shareable", "paragraph", shareable.Id) as List<Paragraph>;
                shareable.FilePaths = await repo.GetItemsOfOwnerAsync<FilePath>("shareable", "filepath", shareable.Id) as List<FilePath>;
            }

            return Json(shareables);
        }
        public IActionResult GetShareablesOfUser()
        {
            int userId = Convert.ToInt32(HttpContext.User.Identity.Name);
            var shareables = _context.GetEntitySet<Shareable>().Where(s => s.UserAccountId == userId).Include(s => s.Paragraphs).Include(s => s.FilePaths).ToList();
            return Json(shareables);
        }

    }
}

ASPracticeCore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using ASPracticeCore.Utils;
@using ASPracticeCore.Areas.Accounts.Models;
@using ASPracticeCore.Repositories;
@using System.Security.Claims;
@inject IHttpContextAccessor HttpContextAccessor

@{
    bool isAuthenticated = HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated;
    string givenName = HttpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == Constants.STRING_GIVEN_NAME)?.Value ?? null;
}

<!DOCTYPE html>
<html>
<head>
    
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["title"]</title>
    <link rel="stylesheet" href="~/css/general.css" asp-append-version="true" />

</head>
<body>

    <nav>
        <a class="logo" href="/Home/Index">ItemInventoryTemplate</a>
        <div class="nav__menu">
            <ul>
                <li><a href="/Home/Index">Home</a></li>
                <li><a href="/Home/About">About</a></li>
                @if (isAuthenticated)
                {
                    <li class="dropdown">
                        Hello, @givenName
                        <div class="dropdown-container">
                            <div class="dropdown-triangle">

                            </div>
                            <ul class="dropdown-list">
                                <li><a href='#'>Manage Profile</a></li>
                                @* <li><a href='@Url.Action("UserShareables", "Shareable")'>My Shareables</a></li> *@
                                <li><a href="/Shareable/UserShareables">My Shareables</a></li>
                                <li><a href='@Url.Action("Logout", "Access", new { Area="Accounts"})'>Logout</a></li>
                            </ul>
                        </div>


                    </li>
                }
                else
                {
                    <li id="login"><a href="/Accounts/Access/Login">Login</a></li>
                }

            </ul>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <script src="~/js/site.js"></script>

    <div id="layout_body">
        @RenderBody()
    </div>

    <footer>

        Template Web App - Lourd Andre B. Ammuyutan.
       
    </footer>


</body>
</html>

ASPracticeCore/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPracticeCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ASPracticeCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ASPracticeCore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>